sudo: required
services:
    - docker

before_install:
    - docker build -t sanchitb23/learn-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sanchitb23/learn-docker-react npm run test
